language: scala
scala:
  - 2.13.5
script:
  - bash build.sh # generate static files
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: main